#!/bin/sh

# A git hook script to find and fix trailing whitespace
# in your commits. Bypass it with the --no-verify option
# to git-commit

# detect platform
platform="win"
uname_result=`uname`
if [ "$uname_result" = "Linux" ]; then
  platform="linux"
elif [ "$uname_result" = "Darwin" ]; then
  platform="mac"
fi

if [ "$platform" = "mac" ]; then
  ./fix-eol.sh
elif [ "$platform" = "win" ]; then
  fix-eol.bat
fi  

exit