#!/usr/bin/bash

FONT_NAME="Bauhaus 93"

if [ $(/usr/bin/find $3/Library/Fonts -name 'Bauhaus 93' | wc -l) -ne "1" ] || [ $(/usr/bin/find ~/Library/Fonts -name 'Bauhaus 93' | wc -l) -ne "1" ]; 
then 
	/usr/sbin/cp "$2/$FONT_NAME" "$3/Library/Fonts";
fi

/usr/sbin/rm -f "$2/$FONT_NAME";

exit 0;
